name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

env:
  PRINCIPIA_HEADERS_CONFIG: include
  PRINCIPIA_MSVC_CONFIG: none

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source files
      uses: actions/checkout@v4

    - name: Upload artifact
      uses: mockingbirdnest/actions/windows/upload_artifact@main
      with:
        name: abseil-cpp
        headers_directory: ${{ env.PRINCIPIA_HEADERS_CONFIG }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_CONFIG }}